GET http://localhost:3000/movies/
###
GET http://localhost:3000/movies/46/
###
POST http://localhost:3000/movies/

{
    "directorId":47,
    "movieName": "Jurassic Park",
    "leadActor": "Jeff Goldblum"
}